- qa/git-autosync/configmaps.yml
- qa/git-autosync/daemonsets.yml
- qa/git-autosync/kustomization.yaml
- qa/kustomization.yaml
- qa/lectern/configmaps.yml
> feat: #413 Added git autosync daemonset

- qa/keycloak/clin-theme.yml
- qa/keycloak/kustomization.yaml
Added clin keycloak theme to orchestration
> feat: #413 Added clin keycloak theme to orchestration

- qa/kustomization.yaml
- qa/spark/kustomization.yaml
> feat: Ferlab-Ste-Justine/clin-project#440 Spark orchestration

- qa/portal/ingresses.yml
> fix: Ferlab-Ste-Justine/cqdg-project#58 Fixed the path for arranger

- common/fluentd/daemonset.yml
- common/fluentd/kustomization.yaml
- local/elasticsearch/deployment.yml
- local/elasticsearch/kustomization.yaml
- local/elasticsearch/service.yml
- local/fluentd/daemonset.yml
- local/fluentd/kustomization.yaml
- local/kustomization.yaml
- local/postgres/deployment.yml
- local/postgres/kustomization.yaml
- local/postgres/service.yml
> feat: Ferlab-Ste-Justine/cqdg-project#23 Added local environment

- qa/certificate/certificate.yml
- qa/kustomization.yaml
- qa/logs/deployments.yml
- qa/logs/ingress.yml
- qa/logs/kustomization.yaml
- qa/logs/services.yml
> feat: Ferlab-Ste-Justine/cqdg-project#23 Added logs access service

- qa/fluentd/access.yml
- qa/fluentd/daemonset.yml
- qa/fluentd/kustomization.yaml
Added fluentd to orchestration
> feat: Ferlab-Ste-Justine/cqdg-project#23 Added fluentd to orchestration

- .github/workflows/commit_lint.yml
- README.md
> feat: Ferlab-Ste-Justine/clin-project#390 Added commit lint pipeline

- qa/kustomization.yaml
- qa/zeppelin/kustomization.yaml
Fixed problems with zeppelin orchestration
> feat: #128 Fixed problems with zeppelin orchestration

- qa/documentation/ingress.yml
- qa/elasticsearch/ingress.yml
- qa/keycloak/ingress.yml
- qa/lectern/ingress.yml
- qa/logs/ingress.yml
- qa/portal/ingresses.yml
- qa/zeppelin/ingress.yml
Switched to temporary certificate
> fix: #128 Switched to temporary certificate

- qa/documentation/ingress.yml
- qa/elasticsearch/ingress.yml
- qa/keycloak/ingress.yml
- qa/lectern/ingress.yml
- qa/logs/ingress.yml
- qa/portal/ingresses.yml
- qa/zeppelin/ingress.yml
Revert -> Switched to temporary certificate
> fix: #128 Revert -> Switched to temporary certificate

- qa/zeppelin/ingress.yml
Adjusted port of zeppelin service
> fix: #128 Adjusted port of zeppelin service

- qa/hive-metastore/kustomization.yaml
- qa/hive-metastore/service.yml
Added nodeport for hive metastore for externa zeppelin driver
> feat: #128 Added nodeport for hive metastore for externa zeppelin driver

- qa/git-autosync/configmaps.yml
- qa/git-autosync/daemonsets.yml
Added cqdg airflow dags repo to git autosync list
> feat: #196 Added cqdg airflow dags repo to git autosync list

- qa/git-autosync/daemonsets.yml
> fix: #196 Typo fix

- qa/airflow/configsmap-override.yml
- qa/airflow/deployments-override.yml
- qa/airflow/ingress.yml
- qa/airflow/kustomization.yaml
- qa/certificate/certificate.yml
- qa/kustomization.yaml
Added airflow orchestration to qa environment
> feat: #196 Added airflow orchestration to qa environment

- qa/kustomization.yaml
Re-added keycloak to orchestration
> feat: #229 Re-added keycloak to orchestration

- qa/git-autosync/configmaps.yml
- qa/git-autosync/daemonsets.yml
Added autosync for keycloak configs repos
> feat: #38 Added autosync for keycloak configs repos

- qa/git-autosync/daemonsets.yml
Fixed git clone fingerprint issue
> fix: #38 Fixed git clone fingerprint issue

- qa/flux-patch.yaml
Cleaned up dangling resource in patch file
> fix: #38 Cleaned up dangling resource in patch file

- qa/terraform/clone.sh
Fixed some foibles in clone script
> fix: #38 Fixed some foibles in clone script

- qa/terraform/apply.sh
Terraform apply script adjustments
> fix: #38 Terraform apply script adjustments

- qa/keycloak/jobs.yml
- qa/keycloak/kustomization.yaml
Added job to configure cqdg keycloak
> feat: #38 Added job to configure cqdg keycloak

- local/keycloak/jars_list.json
- local/keycloak/overrides.yml
- local/upload-binaries/build_list.json
- local/upload-binaries/jobs.yml
- local/upload-binaries/kustomization.yaml
- local/upload-binaries/secrets.yml
Integrated keycloak jar auto-updating in local environment
> feat: #243 Integrated keycloak jar auto-updating in local environment

- qa/keycloak/build_list.json
- qa/keycloak/jobs.yml
- qa/keycloak/kustomization.yaml
Added job to build and push keycloak jars on s3 store
> feat: #243 Added job to build and push keycloak jars on s3 store

- dev/keycloak/jars.yml
- dev/keycloak/jars_list.json
- dev/keycloak/kustomization.yaml
Added jar auto deployment to dev keycloak
> feat: #243 Added jar auto deployment to dev keycloak

- qa/keycloak/jars_list.json
- qa/keycloak/kustomization.yaml
Added missing jars list definition
> fix(CQDG): #243 Added missing jars list definition

- .gitmodules
- local/keycloak/kustomization.yaml
- local/keycloak/overrides.yml
> feat: #243 Changed local to keycloak 12

- .github/workflows/validate.yml
- .gitmodules
- ops/certificate/certificate.yml
- ops/certificate/issuers.yml
- ops/certificate/kustomization.yaml
- ops/kustomization.yaml
Added ops certificate to orchestration
> feat: #244 Added ops certificate to orchestration

- .github/workflows/validate.yml
- ops/.flux.yaml
Added missing flux yaml file for ops environment
> fix: #244 Added missing flux yaml file for ops environment

- ops/certificate/certificate.yml
- ops/certificate/kustomization.yaml
Changed certificate to ceph access control
> feat: #61 Changed certificate to ceph access control

- qa/fluentd/daemonset.yml
Increased fluentd memory request and maximum to 1gb
> fix: #254 Increased fluentd memory request and maximum to 1gb

- qa/airflow/configsmap-override.yml
Added image pull credentials to airflow k8 executor
> feat: #244 Added image pull credentials to airflow k8 executor

- dev/kustomization.yaml
Re-added keycloak to dev orchestration
> feat: #243 Re-added keycloak to dev orchestration

- dev/keycloak/cqdg-keycloak.yml
Added image pull secret to dev keycloak image
> feat: #243 Added image pull secret to dev keycloak image

- dev/keycloak/cqdg-keycloak.yml
> fix: #243 manifest syntax error fix

- qa/flux-patch.yaml
- qa/keycloak/cqdg-keycloak.yml
Temporarily rolled back to previous image
> fix: #259 Temporarily rolled back to previous image

- common/keycloak/kustomization.yml
- common/keycloak/standalone-ha.xml
- dev/keycloak/cqdg-keycloak.yml
- dev/keycloak/kustomization.yaml
Added custom spi fix to standalone config of dev keycloak
> fix: #264 Added custom spi fix to standalone config of dev keycloak

- dev/keycloak/cqdg-keycloak.yml
keycloak-standalone, not kubernetes-standalone
> fix: #264 keycloak-standalone, not kubernetes-standalone

- local/keycloak/clin-themes.yml
- local/keycloak/kustomization.yaml
Added clin theme to local environment
> feat: #264 Added clin theme to local environment

- qa/keycloak/cqdg-keycloak.yml
Restored fluxcd autodeploy for qa keycloak image
> feat: #264 Restored fluxcd autodeploy for qa keycloak image

- qa/arranger/deployments.yml
- qa/arranger/kustomization.yml
revert breaking arranger deployment
> fix: #264 revert breaking arranger deployment

- qa/flux-patch.yaml
Removed cqdg arranger image from flux patch
> fix: #264 Removed cqdg arranger image from flux patch

- dev/arranger/deployments.yml
- dev/arranger/kustomization.yml
> feat: #264 Deploying arrange in dev

- dev/kustomization.yaml
Added missing arranger directory in dev orchestration
> fix: #264 Added missing arranger directory in dev orchestration

- dev/arranger/deployments.yml
Incremented dev arranger image by 1
> fix: #264 Incremented dev arranger image by 1

- dev/flux-patch.yaml
> fix: #264 forced arranger in patch file

- dev/flux-patch.yaml
> fix: #264 Patchfile image fix

- dev/arranger/deployments.yml
- qa/id-service/deployments-overrides.yml
- qa/id-service/kustomization.yaml
- qa/kustomization.yaml
Added id service orchestration for qa
> feat: #264 Added id service orchestration for qa

- qa/id-service/kustomization.yaml
Put the id service in the right namespace
> fix: #264 Put the id service in the right namespace

- dev/certificate/certificate.yml
- dev/kustomization.yaml
- dev/portal/deployments.yml
- dev/portal/ingress.yml
- dev/portal/kustomization.yaml
- dev/portal/services.yml
Added orchestration for new cqdg portal in dev environment
> feat: #264 Added orchestration for new cqdg portal in dev environment

- dev/arranger/deployments.yml
> fix: #264 Config fix

- dev/keycloak/cqdg-keycloak.yml
- qa/keycloak/cqdg-keycloak.yml
Added keycloak orcid url environment variable
> fix: #264 Added keycloak orcid url environment variable

- dev/keycloak/ingress.yml
Set cors policy to be permissive in keycloak dev
> fix: #264 Set cors policy to be permissive in keycloak dev

- dev/keycloak/cqdg-keycloak.yml
Put dev keycloak back to a 3 replicas ha configuration
> feat: #264 Put dev keycloak back to a 3 replicas ha configuration

- qa/arranger/configure-arranger/job.yml
fixed kubectl not liking mountpaths being the same
> fix: #264 fixed kubectl not liking mountpaths being the same

- qa/kustomization.yaml
Added clinical-data to the orchestration list
> fix: #264 Added clinical-data to the orchestration list

- qa/clinical-data/kustomization.yml
added advertised url parameter to clinical data service
> fix: #264 added advertised url parameter to clinical data service

- qa/clinical-data/kustomization.yml
> fix: #264 Added missing variable

- qa/clinical-data/deployments.yml
Increased resource allowance for clinical data service
> fix: #264 Increased resource allowance for clinical data service

- qa/id-service/deployments-overrides.yml
- qa/id-service/kustomization.yaml
Added missing id service customizations
> fix: #264 Added missing id service customizations

- qa/id-service/deployments-overrides.yml
Added configmap that got overwritten
> fix: #264 Added configmap that got overwritten

- qa/id-service/kustomization.yaml
- qa/id-service/migrations/id-service-schema.sql
- qa/id-service/migrations/initialize-schema.yml
- qa/id-service/migrations/kustomization.yaml
Added schema creation for id service
> feat: #264 Added schema creation for id service

- qa/id-service/migrations/initialize-schema.yml
Added missing ca certificate to schema initialization job
> fix: #264 Added missing ca certificate to schema initialization job

- qa/id-service/migrations/initialize-schema.yml
Added missing credentials from id service schema creation
> fix: #264 Added missing credentials from id service schema creation

- qa/clinical-data/deployments.yml
Set clinical data service logs to debug
> fix: #264 Set clinical data service logs to debug

- qa/clinical-data/deployments.yml
Increased clinical data log levels
> fix: #188 Increased clinical data log levels

- qa/clinical-data/deployments.yml
Increased clinical data memory cap
> fix: #188 Increased clinical data memory cap

- qa/clinical-data/deployments.yml
Added cpu capacity to clinical data
> fix: #188 Added cpu capacity to clinical data

- qa/clinical-data/deployments.yml
- qa/clinical-data/ingress.yml
Removed extra nginx flags and increased ram for poc
> fix: #188 Removed extra nginx flags and increased ram for poc

- qa/datagrid-service/backups/backup.yml
- qa/datagrid-service/backups/kustomization.yaml
- qa/datagrid-service/backups/prune-backups.yml
- qa/datagrid-service/deployments-overrides.yml
- qa/datagrid-service/kustomization.yaml
- qa/datagrid-service/migrations/datagrid-service-schema.sql
- qa/datagrid-service/migrations/initialize-schema.yml
- qa/datagrid-service/migrations/kustomization.yaml
- qa/kustomization.yaml
Added orchestration for datagrid service
> feat: #247 Added orchestration for datagrid service

- qa/certificate/certificate.yml
- qa/datagrid-service/ingresses.yml
- qa/datagrid-service/kustomization.yaml
Added datagrid certificate and external access endpoint
> feat: #247 Added datagrid certificate and external access endpoint

- qa/elasticsearch/kustomization.yaml
- qa/elasticsearch/migration/kustomization.yaml
- qa/elasticsearch/migration/migrate.sh
- qa/elasticsearch/migration/migration.yml
> feat: #52 Finalized es migration job

- qa/fluentd/daemonset.yml
Switched logging to new es cluster
> feat: #52 Switched logging to new es cluster

- qa/clinical-data/backups/backup.yml
- qa/clinical-data/backups/kustomization.yaml
- qa/clinical-data/backups/prune-backups.yml
- qa/id-service/backups/backup.yml
- qa/id-service/backups/kustomization.yaml
- qa/id-service/backups/prune-backups.yml
Changed backup destination for id and clinical data services
> feat: #16 Changed backup destination for id and clinical data services

- qa/certificate/certificate.yml
Added ferload subdomain to certificate
> feat: #360 Added ferload subdomain to certificate

- qa/hive-metastore/backups/backup.yml
- qa/hive-metastore/backups/kustomization.yaml
- qa/hive-metastore/backups/prune-backups.yml
- qa/hive-metastore/kustomization.yaml
Added backup cronjob for hive metastore
> feat: #16 Added backup cronjob for hive metastore

- qa/airflow/backups/backup.yml
- qa/airflow/backups/kustomization.yaml
- qa/airflow/backups/prune-backups.yml
- qa/airflow/kustomization.yaml
> feat: #16 Added airflow backup

- qa/datagrid-service/backups/backup.yml
- qa/datagrid-service/backups/kustomization.yaml
- qa/datagrid-service/backups/prune-backups.yml
Changed datagrid backup bucket
> feat: #52 Changed datagrid backup bucket

- qa/airflow/backups/backup.yml
- qa/airflow/backups/prune-backups.yml
- qa/clinical-data/backups/backup.yml
- qa/clinical-data/backups/prune-backups.yml
- qa/datagrid-service/backups/backup.yml
- qa/datagrid-service/backups/prune-backups.yml
- qa/hive-metastore/backups/backup.yml
- qa/hive-metastore/backups/prune-backups.yml
- qa/id-service/backups/backup.yml
- qa/id-service/backups/prune-backups.yml
- qa/keycloak/backups/backup.yml
- qa/keycloak/backups/prune-backups.yml
Changed backup image to use postgres custom backups
> feat: #298 Changed backup image to use postgres custom backups

- qa/airflow/backups/kustomization.yaml
Fixed airflow db name to match certificate
> feat: #298 Fixed airflow db name to match certificate

- qa/airflow/configsmap-override.yml
- qa/airflow/cronjobs-override.yml
- qa/airflow/deployments-override.yml
Added postgres ca volume to airflow orchestrations
> feat: #298 Added postgres ca volume to airflow orchestrations

- qa/id-service/migrations/id-service-schema.sql
- qa/id-service/migrations/initialize-schema.yml
Added index for id service table
> feat: #300 Added index for id service table

- qa/keycloak/cqdg-keycloak.yml
- qa/keycloak/kustomization.yaml
Re-orchestrated keycloak on the new db server
> feat: #298 Re-orchestrated keycloak on the new db server

- qa/keycloak/cqdg-keycloak.yml
Added missing ca certificate to keycloak orchestration
> fix: #298 Added missing ca certificate to keycloak orchestration

- dev/keycloak/cqdg-keycloak.yml
> feat: #298 Switched keycloak dev db

- dev/keycloak/cqdg-keycloak.yml
Added missing ca certificate for postgres
> fix: #298 Added missing ca certificate for postgres

- qa/clinical-data/kustomization.yml
Restarting clinical data service on new db server
> feat: #298 Restarting clinical data service on new db server

- qa/terraform/apply.sh
fixed typo in terraform script
> fix: #370 fixed typo

- qa/keycloak/configure.yml
Changed keycloak config provider secret to generated one
> feat: #370 Changed keycloak config provider secret to generated one

- qa/datagrid-service/kustomization.yaml
> feat: #298 Disabled datagrid service

- qa/flux-patch.yaml
> fix: #298 Cleaned up flux patch entry

- qa/datagrid-service/backups/backup.yml
Increased datagrid backup frequency to every minute
> feat: #298 Increased datagrid backup frequency to every minute

- qa/datagrid-service/kustomization.yaml
- qa/datagrid-service/postgres-override.yml
> feat: #298 Added missing configmap

- qa/datagrid-service/postgres-override.yml
Added another missing configmap
> fix: #298 Added another missing configmap

- qa/datagrid-service/postgres-override.yml
Changed configmap for backup against previous db
> fix: #298 Changed configmap for backup against previous db

- qa/datagrid-service/backups/backup.yml
- qa/datagrid-service/deployments-overrides.yml
- qa/datagrid-service/kustomization.yaml
- qa/datagrid-service/postgres-override.yml
> feat: #298 Re-enabled datagrid service

- qa/datagrid-service/deployments-overrides.yml
fixed wrong secret for datagrid
> fix: #298 fixed wrong secret for datagrid

- qa/elasticsearch/kustomization.yaml
> feat: #387 Disabled es migration

- qa/arranger/kustomization.yml
Disabled arranger configuration for now
> fix: #387 Disabled arranger configuration for now

- qa/hive-metastore/deployments.yml
Updated hive orchestration to latest version of the image
> feat: Updated hive orchestration to latest version of the image

- qa/kustomization.yaml
Changed orchestration to tunneled
> feat: #425 Changed orchestration to tunneled

- qa/datagrid-service/deployments-overrides.yml
> fix: #425 coredns symlink problem fix

- qa/datagrid-service/deployments-overrides.yml
Fixes for datagrid service coredns sidecar orchestration
> fix: #425 Fixes for datagrid service coredns sidecar orchestration

- qa/elasticsearch/configure/cron-job.yml
- qa/elasticsearch/configure/kustomization.yaml
- qa/elasticsearch/configure/provider.tf
- qa/elasticsearch/kustomization.yaml
Added elasticsearch terraform config cron job
> feat: #60 Added elasticsearch terraform config cron job

- qa/apps/fhir-server/dns-overrides.yml
> fix: CQDG-8 Added missing coredns volume

- qa/apps/fhir-server/deployment.yml
Adjusted fhir db credentials secret name
> fix: CQDG-8 Adjusted fhir db credentials secret name

- qa/apps/fhir-server/deployment.yml
Fixed expected fhir db credentials expected secret keys
> fix: CQDG-8 Fixed expected fhir db credentials expected secret keys
